services:
  - type: web
    name: imageprocessing-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false