import { jsPDF } from 'jspdf';
import { VehicleProcessingReport } from '../types';

export function generatePdfReport(report: VehicleProcessingReport) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 32, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('AutoVision AI Vehicle Inspection Audit', 14, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text(`Processing ID: ${report.processing_id} | Date: ${report.upload_time}`, 14, 22);
  doc.text('Computer Vision • OCR • Laplacian Blur • Media Forensics • Gemini Agent', 14, 27);

  let y = 42;

  // Section 1: Executive Summary & AI Findings
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(14, y, 182, 36, 2, 2, 'F');

  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Gemini AI Agent Executive Summary', 18, y + 8);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);

  const splitSummary = doc.splitTextToSize(report.ai_summary, 174);
  doc.text(splitSummary, 18, y + 16);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(217, 119, 6); // amber-600
  doc.text(`Suitability Determination: ${report.ai_suitability || 'Verified'}`, 18, y + 31);

  y += 44;

  // Section 2: Vehicle Specs & OCR
  doc.setFillColor(30, 41, 59);
  doc.rect(14, y, 182, 7, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('1. VEHICLE CLASSIFICATION & LICENSE PLATE OCR', 18, y + 5);

  y += 12;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);

  const col1X = 18;
  const col2X = 110;

  doc.text(`Vehicle Category: ${report.vehicle_category}`, col1X, y);
  doc.text(`Manufacturer: ${report.manufacturer}`, col1X, y + 6);
  doc.text(`Model: ${report.model}`, col1X, y + 12);
  doc.text(`Color & Year: ${report.vehicle_color}, ~${report.estimated_year}`, col1X, y + 18);

  doc.text(`License Plate: ${report.number_plate}`, col2X, y);
  doc.text(`Plate Valid: ${report.plate_valid ? 'YES (Indian HSRP Format)' : 'NO (Invalid Format)'}`, col2X, y + 6);
  doc.text(`OCR Confidence: ${report.ocr_confidence}%`, col2X, y + 12);
  doc.text(`RTO Office: ${report.district_name || 'N/A'} (${report.state_name || 'N/A'})`, col2X, y + 18);

  y += 28;

  // Section 3: Image Quality & Blur Metrics
  doc.setFillColor(30, 41, 59);
  doc.rect(14, y, 182, 7, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('2. OPENCV QUALITY & LAPLACIAN BLUR ANALYSIS', 18, y + 5);

  y += 12;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);

  doc.text(`Overall Quality: ${report.image_quality}`, col1X, y);
  doc.text(`Laplacian Blur Score: ${report.blur_score} (${report.blur_category || 'Sharp'})`, col1X, y + 6);
  doc.text(`Brightness / Contrast: ${report.brightness} / ${report.contrast}`, col1X, y + 12);

  doc.text(`Noise Level: ${report.noise}`, col2X, y);
  doc.text(`Resolution: ${report.quality_details?.resolution || '3840 x 2160'}`, col2X, y + 6);

  y += 22;

  // Section 4: Security, ELA & EXIF
  doc.setFillColor(30, 41, 59);
  doc.rect(14, y, 182, 7, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('3. MEDIA FORENSICS & AUTHENTICITY', 18, y + 5);

  y += 12;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);

  doc.text(`Digital Tampering (ELA): ${report.tampered ? 'ALERT: TAMPERED' : 'CLEAN'}`, col1X, y);
  doc.text(`Screenshot Detected: ${report.screenshot ? 'YES (Screen Capture)' : 'NO (Live Photo)'}`, col1X, y + 6);
  doc.text(`Duplicate Record: ${report.duplicate ? 'YES' : 'NO'}`, col1X, y + 12);

  doc.text(`Camera: ${report.metadata?.camera || 'N/A'}`, col2X, y);
  doc.text(`GPS Coords: ${report.metadata?.gps || 'N/A'}`, col2X, y + 6);
  doc.text(`Capture Time: ${report.metadata?.capture_time || 'N/A'}`, col2X, y + 12);

  y += 28;

  // Footer
  doc.setDrawColor(203, 213, 225);
  doc.line(14, 275, 196, 275);
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by AutoVision AI Computer Vision Platform | Powered by Google Gemini', 14, 281);

  doc.save(`AutoVision_Report_${report.processing_id}.pdf`);
}
